version: '3'
services:
  node_1:
    image: prom/node-exporter
    container_name: node_1
    privileged: true
    restart: always
    ports:
      - "9100:9100"

  blackbox_1:
    image: prom/blackbox-exporter
    container_name: blackbox_1
    privileged: true
    restart: always
    ports: 
      - "9115:9115"
    volumes:
      - ./blackbox_exporter:/etc/blackbox_exporter
  
  alert_1:
    image: prom/alertmanager
    container_name: alertmanager_1
    privileged: true
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager_exporter/alertmanager.yml:/etc/alertmanager_exporter/alertmanager.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    privileged: true
    restart: always
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    privileged: true
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      